Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -26,15 +26,37 @@ jobs:
     - name: Test
       run: dotnet test --no-build --verbosity normal
     
+    - name: Extract Version
+      id: extract_version
+      run: |
+        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+          VERSION=${GITHUB_REF#refs/tags/v}
+          echo "Version: $VERSION"
+          echo "version=$VERSION" >> $GITHUB_ENV
+        else
+          echo "No valid version found."
+          echo "version=" >> $GITHUB_ENV
+        fi
+
+    - name: Validate Version
+      id: validate_version
+      run: |
+        if [[ "${{ env.version }}" != "" ]]; then
+          if [[ ! "${{ env.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Version format is invalid. Should be in the format x.y.z"
+            exit 1
+          fi
+        else
+          echo "No valid version found. Skipping pack and publish."
+          exit 0
+        fi
+
     - name: Pack the NuGet package
       id: pack
+      if: ${{ env.version != '' && env.version =~ '^[0-9]+\.[0-9]+\.[0-9]+$' }}  # Only run if the version is valid
       run: |
-        # Extract the version from the tag
-        VERSION=${GITHUB_REF#refs/tags/v}
-        echo "Version: $VERSION"
+        dotnet pack --configuration Release --output ./nupkg /p:Version=${{ env.version }}
 
-        # Pack the NuGet package with the extracted version
-        dotnet pack --configuration Release --output ./nupkg /p:Version=$VERSION
-        
     - name: Publish to GitHub Packages
+      if: steps.pack.outcome == 'success'  # Only run this step if the packing succeeded
       run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.MY_GITHUB_TOKEN }}
